USE sealthenote;

CREATE TABLE IF NOT EXISTS NoteContent(
id CHAR(60) NOT NULL PRIMARY KEY,
noteText CHAR(60) NOT NULL
);
CREATE TABLE IF NOT EXISTS Tag(
id CHAR(60) NOT NULL PRIMARY KEY,
tagName CHAR(60) NOT NULL,
idUser CHAR(60) NOT NULL
);
CREATE TABLE IF NOT EXISTS User (
id CHAR(60) NOT NULL PRIMARY KEY,
userName CHAR(60),
userEmail CHAR(60) NOT NULL,
userPassw CHAR(60) NOT NULL,
userBirthDate CHAR(60),
avatar CHAR(60)
);
CREATE TABLE IF NOT EXISTS Note(
id CHAR(60) NOT NULL PRIMARY KEY,
idUser CHAR(60) NOT NULL,
noteName CHAR(60) NOT NULL,
tagId CHAR(60) NOT NULL,
noteContentId CHAR(60),
notePassword CHAR(60),
FOREIGN KEY(tagId) REFERENCES Tag(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(noteContentId) REFERENCES NoteContent(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(idUser) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);
